[book]
authors = ["Carl Fredrik Samson"]
language = "en"
multilingual = false
src = "src"
title = "Investigating Async Basics - Implementing the Node.js Eventloop in Rust"
[output.html]
theme = "src/theme"
