[book]
authors = ["Carl Fredrik Samson"]
language = "en"
multilingual = false
src = "src" 
title = "The Node Experiment - Exploring Async Basics with Rust"

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/cfsamson/book-investigating-async-basics"
google-analytics = "142049002"
